travis:
  secure:
    BINSTAR_TOKEN: m6nJZTg2+8iLtYEghVaH5cyR4WpooiezeUrQl6ySJZud1CxKIzr88dN1vPUhgRwofJy0zSomZsOiDK5tbbD3iQgvXc03XoTcbnkbudQVmKqc+lVT06qgoyBdMT/gyTiTLjyw5DVpKNZf73guc08kvLNNZUn3YqTyBbMuVhSsb2bJiQ05QlOE1UjpQqSEyovWcP7F3kkfE9G1mzQXybyL71b5Gl7J7H66NXndmnizJKVyFHuZOjy5GxSrEYImOXh/sacMB1Zflu00O2rpPHQL6JioOJSyVlat09tHfDLTCPICpyVu6hpNiL5RWw1P+iAtjqnq8Sk4R9cMdUhqcQNdp2OoE9rX8tI5kjGJx522PC73png2r7SJ3zVb1Trdg2aLdjAszVwc7ZnsaXxTmDLz4YcwUyEzCIT/3R8M3qyL/2MWt7ZfVikYUD1ezpwbT2MbKenwu3NXZ8SLMGJMPCxdrLZhmw+irHlZb353ZHTfeL7q8w+FCaLIVinVIcwEzdRlfd+3K2c4r8nXIpFOrAMyfqeacZTAyMt0+7wGHfaegX+2fomYC8lvIdujl0mIZE1B/9dF6qpiX75vIO3DiaG+cE5QZJfaVR5eBhFYGIH5qzEYLQthBuGN96ozmQ20hpkeS4ClsNbyJsCxNxNLYckB8h0M7xkts0Rt0rdITCAvHjQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
